name: flutter_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  # carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  get: ^4.7.3
  shared_preferences: ^2.3.3
  go_router: ^17.0.1
  google_fonts: ^7.0.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.2
  path_provider: ^2.1.5
  pull_to_refresh: ^2.0.0
  sqflite: ^2.4.2
  carousel_slider_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/icons/
    # - assets/lottie/
    # - assets/fonts/
    # - assets/videos/
    - .env.development
    - .env.production